# Generated by Django 5.0.6 on 2025-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_encryptionperformance_delete_verificationtestfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptionPerformance',
        ),
    ]
