# Generated by Django 5.1.6 on 2025-02-19 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDetails',
            fields=[
                ('fileid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(max_length=64)),
                ('owneremail', models.EmailField(max_length=254)),
                ('ownername', models.CharField(max_length=255)),
                ('case_number', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('evidence_file', models.FileField(upload_to='evidencefiles/')),
                ('encryption_key', models.TextField()),
                ('evidence_description', models.TextField()),
                ('status', models.CharField(default='requested', max_length=50)),
            ],
            options={
                'db_table': 'evidence_details',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
    ]
