# Generated by Django 5.1.6 on 2025-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='encryption_key',
            new_name='aes_key',
        ),
    ]
