# Generated by Django 5.1.6 on 2025-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_encryption_key_usermodel_aes_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
