# Generated by Django 4.2.18 on 2025-02-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_usermodel_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenceDetails',
        ),
    ]
