# Generated by Django 4.2.18 on 2025-02-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_delete_evidencedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('owneremail', models.EmailField(max_length=254)),
                ('ownername', models.CharField(max_length=255)),
                ('case_number', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(max_length=255)),
                ('evidence_description', models.TextField()),
                ('filename', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='static\\EnTextFiles')),
                ('encrypted_data', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'db_table': 'EvidenceDetails',
            },
        ),
    ]
