# Generated by Django 4.2.18 on 2025-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_evidencedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedetails',
            name='status',
            field=models.CharField(default='Encrypted', max_length=100),
        ),
    ]
