# Generated by Django 4.2.18 on 2025-02-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_evidencedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
