# Generated by Django 4.2.18 on 2025-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_usermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedetails',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
