# Generated by Django 4.2.20 on 2025-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_evidencedetails_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedetails',
            name='file_path',
            field=models.FileField(upload_to='static/EnTextFiles'),
        ),
        migrations.AlterField(
            model_name='evidencedetails',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
