# Generated by Django 5.0.6 on 2025-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_evidencedetails_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedetails',
            name='file_path',
            field=models.FileField(upload_to='static\\EnTextFiles'),
        ),
    ]
